name: DataSci
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - rapids-blazing=0.17 
  - python=3.8 
  - cudatoolkit=11.0
  - numpy=1.19.2
  - pandas=1.1.3
  - scikit-learn=0.23.2
  - sphinx=3.2.1
  - pip:
    - torch==1.7.1
    - dash==1.18.1
    - gpustat==0.6.0
    - imblearn==0.0
    - missingpy==0.2.0
    - seaborn==0.11.1
    - matplotlib==3.3.3
    - pydataset==0.2.0
    - plotly==4.11.0
    - umap-learn==0.4.6
    - sphinx-rtd-theme==0.5.1
